### ISSUE TITLE
neo4j

### ISSUE THREAD

**Issue by pandeysudhanshu** [Octavian-ai/english2cypher#7]
neo4j connection is not working

**Comment by davidhughhenrymack** [comment]
Hi,

Any more information about what error you get, your local setup?

**Comment by pandeysudhanshu** [comment]
when i run start-neo4j-database.sh    
i get this error
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by davidhughhenrymack** [comment]
Ah, you need to have a look at the Docker documentation for that error, or
not use Docker for local neo4j


On March 5, 2019 at 6:29:52 AM, pandeysudhanshu (notifications@github.com)
wrote:

when i run start-neo4j-database.sh
i get this error
docker: Got permission denied while trying to connect to the Docker daemon
socket at unix:///var/run/docker.sock: Post
http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/create:
dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Octavian-ai/english2cypher/issues/7#issuecomment-469700337>,
or mute the thread

**Comment by pandeysudhanshu** [comment]
Thank you.
but i get this error when i run ->     python -m e2c.predict --neo-user neo4j --neo-password pandey --neo-url http://localhost:7474
Traceback (most recent call last):
  File "/home/sudhanshu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sudhanshu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sudhanshu/Desktop/english2cypher-master/e2c/predict.py", line 118, in <module>
    with Neo4jSession(args) as session:
  File "/home/sudhanshu/Desktop/english2cypher-master/db/execute.py", line 24, in __enter__
    encrypted=False)
  File "/home/sudhanshu/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 108, in driver
    return Driver(uri, **config)
  File "/home/sudhanshu/anaconda3/lib/python3.7/site-packages/neo4j/__init__.py", line 148, in __new__
    raise ValueError("URI scheme %r not supported" % parsed.scheme)
ValueError: URI scheme 'http' not supported

**Comment by pandeysudhanshu** [comment]
it worked !
